name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - 
      name: CHeckout
      uses: actions/checkout@v2
    
    - 
      name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: user/app:latest
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
